# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifS2wZUgpMLaquh3b8HRyqzht0CI2QqN
"""

import streamlit as st
import pandas as pd
import numpy as np
import time

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression

# =========================
# KONFIGURASI HALAMAN
# =========================
st.set_page_config(
    page_title="Deteksi Alzheimer Lansia",
    page_icon="🧠",
    layout="centered"
)

st.title("🧠 Sistem Deteksi Risiko Alzheimer pada Lansia")
st.caption("Berbasis Machine Learning (Logistic Regression)")

st.divider()

# =========================
# LOAD & TRAIN MODEL
# =========================
@st.cache_resource
def load_model():
    df = pd.read_csv("alzheimers_disease_data.csv")

    fitur = [
        "Age",
        "MMSE",
        "FunctionalAssessment",
        "MemoryComplaints",
        "BehavioralProblems",
        "ADL"
    ]

    target = "Diagnosis"

    df = df[fitur + [target]]
    df = df[df["Age"] >= 60]

    le = LabelEncoder()
    df[target] = le.fit_transform(df[target])

    X = df.drop(target, axis=1)
    y = df[target]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)

    model = LogisticRegression(max_iter=1000)
    model.fit(X_train_scaled, y_train)

    return model, scaler, le

model, scaler, label_encoder = load_model()

# =========================
# INPUT USER
# =========================
st.subheader("Input Data Pasien")

age = st.number_input("Usia (≥ 60 tahun)", min_value=60, max_value=120, value=65)
mmse = st.slider("Skor MMSE", 0, 30)
adl = st.slider("Skor Aktivitas Harian (ADL)", 0, 10)
functional = st.slider("Skor Fungsi Kognitif", 0, 10)
memory = st.radio("Keluhan Memori", ["Tidak", "Ya"])
behavior = st.radio("Masalah Perilaku", ["Tidak", "Ya"])

st.divider()

# =========================
# PREDIKSI
# =========================
if st.button("Deteksi Risiko"):
    with st.spinner("Memproses data..."):
        time.sleep(1)

        input_data = np.array([[
            age,
            mmse,
            functional,
            1 if memory == "Ya" else 0,
            1 if behavior == "Ya" else 0,
            adl
        ]])

        input_scaled = scaler.transform(input_data)
        pred = model.predict(input_scaled)[0]
        prob = model.predict_proba(input_scaled)[0][pred]

        hasil = label_encoder.inverse_transform([pred])[0]

    st.subheader("Hasil Deteksi")

    if hasil == "Alzheimer":
        st.error(f"Risiko Alzheimer terdeteksi ({prob:.1%})")
        st.write(
            "Indikasi menunjukkan kemungkinan penyakit Alzheimer. "
            "Disarankan untuk segera melakukan pemeriksaan lanjutan."
        )

    elif hasil == "MCI":
        st.warning(f"MCI – Gangguan Kognitif Ringan ({prob:.1%})")
        st.write(
            "MCI adalah kondisi penurunan kognitif ringan yang berada "
            "di antara normal dan Alzheimer. Perlu pemantauan rutin."
        )

    else:
        st.success(f"Kondisi Kognitif Normal ({prob:.1%})")
        st.write(
            "Tidak ditemukan indikasi gangguan kognitif yang signifikan."
        )

st.divider()
st.caption("⚠️ Sistem ini hanya digunakan sebagai alat bantu skrining awal.")